DROP TABLE IF EXISTS Doc;
DROP TABLE IF EXISTS Word;

CREATE TABLE Word (
  id INTEGER PRIMARY KEY,
  word VARCHAR(20) NOT NULL
);

CREATE TABLE Doc (
  id INTEGER PRIMARY KEY,
  doc INTEGER NOT NULL
);

CREATE TABLE Token (
  id INTEGER PRIMARY KEY,
  word INTEGER NOT NULL REFERENCES Word(id),
  doc INTEGER NOT NULL REFERENCES Doc(id),
  topic INTEGER NOT NULL);